<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <AssemblyName>GhostStatueMod</AssemblyName>
    <RootNamespace>GhostStatueMod</RootNamespace>
    <LangVersion>latest</LangVersion>
    <EnableModApiProjectReferences>true</EnableModApiProjectReferences>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SMAPI.ModBuildConfig" Version="4.0.0" />
  </ItemGroup>

</Project>
