<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <AssemblyName>GhostStatueMod</AssemblyName>
    <RootNamespace>GhostStatueMod</RootNamespace>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="StardewValley">
      <HintPath>lib/StardewValley.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SMAPI">
      <HintPath>lib/SMAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="xTile">
      <HintPath>lib/xTile.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
